name: god_engine
version: 0.1.0
description: >
  An experimental virtual reality engine for the web. A sample game can be found at https://github.com/BitAlchemists/AsteroidRacers
author: Tommi Enenkel <tommi.enenkel@gmail.com>
homepage: https://github.com/BitAlchemists/god_engine
dependencies:
  vector_math: 1.1.0
  game_loop: 0.8.0